import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Calculator from "@/modules/calculator";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Tahfiz Bootcamp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={`${styles.center} ${inter.className}`}>
          <Calculator />
        </div>
      </main>
    </>
  );
}

/**
 * Input:
 * 1. Pilih berapa banyak yang ingin dihafal
 * 2. Pilih target waktu
 *
 * Output:
 * 1. Jumlah ayat yang harus dihafal per hari
 *
 */
