export const Juz = [
  {
    id: "juz1",
    label: "Juz 1",
    numberOfAyah: 148,
    range: {
      start: {
        surah: 1,
        ayah: 1,
      },
      end: {
        surah: 2,
        ayah: 141,
      },
    },
  },
  {
    id: "juz2",
    label: "Juz 2",
    numberOfAyah: 111,
    range: {
      start: {
        surah: 2,
        ayah: 142,
      },
      end: {
        surah: 2,
        ayah: 252,
      },
    },
  },
  {
    id: "juz3",
    label: "Juz 3",
    numberOfAyah: 125,
    range: {
      start: {
        surah: 2,
        ayah: 253,
      },
      end: {
        surah: 3,
        ayah: 91,
      },
    },
  },
  {
    id: "juz4",
    label: "Juz 4",
    numberOfAyah: 132,
    range: {
      start: {
        surah: 3,
        ayah: 92,
      },
      end: {
        surah: 4,
        ayah: 23,
      },
    },
  },
  {
    id: "juz5",
    label: "Juz 5",
    numberOfAyah: 124,
    range: {
      start: {
        surah: 4,
        ayah: 24,
      },
      end: {
        surah: 4,
        ayah: 147,
      },
    },
  },
  {
    id: "juz6",
    label: "Juz 6",
    numberOfAyah: 111,
    range: {
      start: {
        surah: 4,
        ayah: 148,
      },
      end: {
        surah: 5,
        ayah: 82,
      },
    },
  },
  {
    id: "juz7",
    label: "Juz 7",
    numberOfAyah: 148,
    range: {
      start: {
        surah: 5,
        ayah: 83,
      },
      end: {
        surah: 6,
        ayah: 110,
      },
    },
  },
  {
    id: "juz8",
    label: "Juz 8",
    numberOfAyah: 142,
    range: {
      start: {
        surah: 6,
        ayah: 111,
      },
      end: {
        surah: 7,
        ayah: 87,
      },
    },
  },
  {
    id: "juz9",
    label: "Juz 9",
    numberOfAyah: 159,
    range: {
      start: {
        surah: 7,
        ayah: 88,
      },
      end: {
        surah: 8,
        ayah: 40,
      },
    },
  },
  {
    id: "juz10",
    label: "Juz 10",
    numberOfAyah: 128,
    range: {
      start: {
        surah: 8,
        ayah: 41,
      },
      end: {
        surah: 9,
        ayah: 93,
      },
    },
  },
  {
    id: "juz11",
    label: "Juz 11",
    numberOfAyah: 150,
    range: {
      start: {
        surah: 9,
        ayah: 94,
      },
      end: {
        surah: 11,
        ayah: 5,
      },
    },
  },
  {
    id: "juz12",
    label: "Juz 12",
    numberOfAyah: 170,
    range: {
      start: {
        surah: 11,
        ayah: 6,
      },
      end: {
        surah: 12,
        ayah: 52,
      },
    },
  },
  {
    id: "juz13",
    label: "Juz 13",
    numberOfAyah: 154,
    range: {
      start: {
        surah: 12,
        ayah: 53,
      },
      end: {
        surah: 14,
        ayah: 52,
      },
    },
  },
  {
    id: "juz14",
    label: "Juz 14",
    numberOfAyah: 227,
    range: {
      start: {
        surah: 15,
        ayah: 1,
      },
      end: {
        surah: 16,
        ayah: 128,
      },
    },
  },
  {
    id: "juz15",
    label: "Juz 15",
    numberOfAyah: 185,
    range: {
      start: {
        surah: 17,
        ayah: 1,
      },
      end: {
        surah: 18,
        ayah: 74,
      },
    },
  },
  {
    id: "juz16",
    label: "Juz 16",
    numberOfAyah: 269,
    range: {
      start: {
        surah: 18,
        ayah: 75,
      },
      end: {
        surah: 20,
        ayah: 135,
      },
    },
  },
  {
    id: "juz17",
    label: "Juz 17",
    numberOfAyah: 190,
    range: {
      start: {
        surah: 21,
        ayah: 1,
      },
      end: {
        surah: 22,
        ayah: 78,
      },
    },
  },
  {
    id: "juz18",
    label: "Juz 18",
    numberOfAyah: 202,
    range: {
      start: {
        surah: 23,
        ayah: 1,
      },
      end: {
        surah: 25,
        ayah: 20,
      },
    },
  },
  {
    id: "juz19",
    label: "Juz 19",
    numberOfAyah: 339,
    range: {
      start: {
        surah: 27,
        ayah: 56,
      },
      end: {
        surah: 29,
        ayah: 45,
      },
    },
  },
  {
    id: "juz20",
    label: "Juz 20",
    numberOfAyah: 171,
    range: {
      start: {
        surah: 27,
        ayah: 56,
      },
      end: {
        surah: 29,
        ayah: 45,
      },
    },
  },
  {
    id: "juz21",
    label: "Juz 21",
    numberOfAyah: 178,
    range: {
      start: {
        surah: 29,
        ayah: 46,
      },
      end: {
        surah: 33,
        ayah: 30,
      },
    },
  },
  {
    id: "juz22",
    label: "Juz 22",
    numberOfAyah: 169,
    range: {
      start: {
        surah: 33,
        ayah: 31,
      },
      end: {
        surah: 36,
        ayah: 27,
      },
    },
  },
  {
    id: "juz23",
    label: "Juz 23",
    numberOfAyah: 357,
    range: {
      start: {
        surah: 36,
        ayah: 28,
      },
      end: {
        surah: 39,
        ayah: 31,
      },
    },
  },
  {
    id: "juz24",
    label: "Juz 24",
    numberOfAyah: 175,
    range: {
      start: {
        surah: 39,
        ayah: 32,
      },
      end: {
        surah: 41,
        ayah: 46,
      },
    },
  },
  {
    id: "juz25",
    label: "Juz 25",
    numberOfAyah: 241,
    range: {
      start: {
        surah: 41,
        ayah: 47,
      },
      end: {
        surah: 45,
        ayah: 32,
      },
    },
  },
  {
    id: "juz26",
    label: "Juz 26",
    numberOfAyah: 200,
    range: {
      start: {
        surah: 45,
        ayah: 33,
      },
      end: {
        surah: 51,
        ayah: 30,
      },
    },
  },
  {
    id: "juz27",
    label: "Juz 27",
    numberOfAyah: 399,
    range: {
      start: {
        surah: 51,
        ayah: 31,
      },
      end: {
        surah: 57,
        ayah: 29,
      },
    },
  },
  {
    id: "juz28",
    label: "Juz 28",
    numberOfAyah: 137,
    range: {
      start: {
        surah: 58,
        ayah: 1,
      },
      end: {
        surah: 66,
        ayah: 12,
      },
    },
  },
  {
    id: "juz29",
    label: "Juz 29",
    numberOfAyah: 431,
    range: {
      start: {
        surah: 67,
        ayah: 1,
      },
      end: {
        surah: 77,
        ayah: 50,
      },
    },
  },
  {
    id: "juz30",
    label: "Juz 30",
    numberOfAyah: 564,
    range: {
      start: {
        surah: 78,
        ayah: 1,
      },
      end: {
        surah: 114,
        ayah: 6,
      },
    },
  },
];

export const Surah = [
  {
    id: "surah_1",
    no: "1",
    name: "Al-Fatihah",
    arabicName: "الفاتحة",
    numberOfAyah: "7",
    meaning: "Pembukaan",
    category: "Makiyah",
  },
  {
    id: "surah_2",
    no: "2",
    name: "Al-Baqarah",
    arabicName: "البقرة",
    numberOfAyah: "286",
    meaning: "Sapi",
    category: "Madaniyah",
  },
  {
    id: "surah_3",
    no: "3",
    name: "Ali 'Imran",
    arabicName: "اٰل عمران",
    numberOfAyah: "200",
    meaning: "Keluarga Imran",
    category: "Madaniyah",
  },
  {
    id: "surah_4",
    no: "4",
    name: "An-Nisa'",
    arabicName: "النساۤء",
    numberOfAyah: "176",
    meaning: "Wanita",
    category: "Madaniyah",
  },
  {
    id: "surah_5",
    no: "5",
    name: "Al-Ma'idah",
    arabicName: "الماۤئدة",
    numberOfAyah: "120",
    meaning: "Hidangan",
    category: "Madaniyah",
  },
  {
    id: "surah_6",
    no: "6",
    name: "Al-An'am",
    arabicName: "الأنعام",
    numberOfAyah: "165",
    meaning: "Binatang Ternak",
    category: "Makiyah",
  },
  {
    id: "surah_7",
    no: "7",
    name: "Al-A'raf",
    arabicName: "الأعراف",
    numberOfAyah: "206",
    meaning: "Tempat Tertinggi",
    category: "Madaniyah",
  },
  {
    id: "surah_8",
    no: "8",
    name: "Al-Anfal",
    arabicName: "الأنفال",
    numberOfAyah: "75",
    meaning: "Rampasan Perang",
    category: "Madaniyah",
  },
  {
    id: "surah_9",
    no: "9",
    name: "At-Taubah",
    arabicName: "التوبة",
    numberOfAyah: "129",
    meaning: "Pengampunan",
    category: "Makiyah",
  },
  {
    id: "surah_10",
    no: "10",
    name: "Yunus",
    arabicName: "يونس",
    numberOfAyah: "109",
    meaning: "Yunus",
    category: "Makiyah",
  },
  {
    id: "surah_11",
    no: "11",
    name: "Hud",
    arabicName: "هود",
    numberOfAyah: "123",
    meaning: "Hud",
    category: "Makiyah",
  },
  {
    id: "surah_12",
    no: "12",
    name: "Yusuf",
    arabicName: "يوسف",
    numberOfAyah: "111",
    meaning: "Yusuf",
    category: "Madaniyah",
  },
  {
    id: "surah_13",
    no: "13",
    name: "Ar-Ra'd",
    arabicName: "الرّعد",
    numberOfAyah: "43",
    meaning: "Guruh",
    category: "Makiyah",
  },
  {
    id: "surah_14",
    no: "14",
    name: "Ibrahim",
    arabicName: "إبرٰهيم",
    numberOfAyah: "52",
    meaning: "Ibrahim",
    category: "Makiyah",
  },
  {
    id: "surah_15",
    no: "15",
    name: "Al-Hijr",
    arabicName: "الحجر",
    numberOfAyah: "99",
    meaning: "Hijr",
    category: "Makiyah",
  },
  {
    id: "surah_16",
    no: "16",
    name: "An-Nahl",
    arabicName: "النحل",
    numberOfAyah: "128",
    meaning: "Lebah",
    category: "Makiyah",
  },
  {
    id: "surah_17",
    no: "17",
    name: "Al-Isra'",
    arabicName: "الإسراۤء",
    numberOfAyah: "111",
    meaning: "Memperjalankan Malam Hari",
    category: "Makiyah",
  },
  {
    id: "surah_18",
    no: "18",
    name: "Al-Kahf",
    arabicName: "الكهف",
    numberOfAyah: "110",
    meaning: "Goa",
    category: "Makiyah",
  },
  {
    id: "surah_19",
    no: "19",
    name: "Maryam",
    arabicName: "مريم",
    numberOfAyah: "98",
    meaning: "Maryam",
    category: "Makiyah",
  },
  {
    id: "surah_20",
    no: "20",
    name: "Taha",
    arabicName: "طٰهٰ",
    numberOfAyah: "135",
    meaning: "Taha",
    category: "Makiyah",
  },
  {
    id: "surah_21",
    no: "21",
    name: "Al-Anbiya'",
    arabicName: "الأنبياۤء",
    numberOfAyah: "112",
    meaning: "Para Nabi",
    category: "Madaniyah",
  },
  {
    id: "surah_22",
    no: "22",
    name: "Al-Hajj",
    arabicName: "الحج",
    numberOfAyah: "78",
    meaning: "Haji",
    category: "Makiyah",
  },
  {
    id: "surah_23",
    no: "23",
    name: "Al-Mu'minun",
    arabicName: "المؤمنون",
    numberOfAyah: "118",
    meaning: "Orang-Orang Mukmin",
    category: "Madaniyah",
  },
  {
    id: "surah_24",
    no: "24",
    name: "An-Nur",
    arabicName: "النّور",
    numberOfAyah: "64",
    meaning: "Cahaya",
    category: "Makiyah",
  },
  {
    id: "surah_25",
    no: "25",
    name: "Al-Furqan",
    arabicName: "الفرقان",
    numberOfAyah: "77",
    meaning: "Pembeda",
    category: "Makiyah",
  },
  {
    id: "surah_26",
    no: "26",
    name: "Asy-Syu'ara'",
    arabicName: "الشعراۤء",
    numberOfAyah: "227",
    meaning: "Para Penyair",
    category: "Makiyah",
  },
  {
    id: "surah_27",
    no: "27",
    name: "An-Naml",
    arabicName: "النمل",
    numberOfAyah: "93",
    meaning: "Semut-semut",
    category: "Makiyah",
  },
  {
    id: "surah_28",
    no: "28",
    name: "Al-Qasas",
    arabicName: "القصص",
    numberOfAyah: "88",
    meaning: "Kisah-Kisah",
    category: "Makiyah",
  },
  {
    id: "surah_29",
    no: "29",
    name: "Al-'Ankabut",
    arabicName: "العنكبوت",
    numberOfAyah: "69",
    meaning: "Laba-Laba",
    category: "Makiyah",
  },
  {
    id: "surah_30",
    no: "30",
    name: "Ar-Rum",
    arabicName: "الرّوم",
    numberOfAyah: "60",
    meaning: "Romawi",
    category: "Makiyah",
  },
  {
    id: "surah_31",
    no: "31",
    name: "Luqman",
    arabicName: "لقمٰن",
    numberOfAyah: "34",
    meaning: "Luqman",
    category: "Makiyah",
  },
  {
    id: "surah_32",
    no: "32",
    name: "As-Sajdah",
    arabicName: "السّجدة",
    numberOfAyah: "30",
    meaning: "Sajdah",
    category: "Madaniyah",
  },
  {
    id: "surah_33",
    no: "33",
    name: "Al-Ahzab",
    arabicName: "الأحزاب",
    numberOfAyah: "73",
    meaning: "Golongan Yang Bersekutu",
    category: "Makiyah",
  },
  {
    id: "surah_34",
    no: "34",
    name: "Saba'",
    arabicName: "سبأ",
    numberOfAyah: "54",
    meaning: "Saba'",
    category: "Makiyah",
  },
  {
    id: "surah_35",
    no: "35",
    name: "Fatir",
    arabicName: "فاطر",
    numberOfAyah: "45",
    meaning: "Maha Pencipta",
    category: "Makiyah",
  },
  {
    id: "surah_36",
    no: "36",
    name: "Yasin",
    arabicName: "يٰسۤ",
    numberOfAyah: "83",
    meaning: "Yasin",
    category: "Makiyah",
  },
  {
    id: "surah_37",
    no: "37",
    name: "As-Saffat",
    arabicName: "الصّٰۤفّٰت",
    numberOfAyah: "182",
    meaning: "Barisan-Barisan",
    category: "Makiyah",
  },
  {
    id: "surah_38",
    no: "38",
    name: "Sad",
    arabicName: "ص",
    numberOfAyah: "88",
    meaning: "Sad",
    category: "Makiyah",
  },
  {
    id: "surah_39",
    no: "39",
    name: "Az-Zumar",
    arabicName: "الزمر",
    numberOfAyah: "75",
    meaning: "Rombongan",
    category: "Makiyah",
  },
  {
    id: "surah_40",
    no: "40",
    name: "Gafir",
    arabicName: "غافر",
    numberOfAyah: "85",
    meaning: "Maha Pengampun",
    category: "Makiyah",
  },
  {
    id: "surah_41",
    no: "41",
    name: "Fussilat",
    arabicName: "فصّلت",
    numberOfAyah: "54",
    meaning: "Yang Dijelaskan",
    category: "Makiyah",
  },
  {
    id: "surah_42",
    no: "42",
    name: "Asy-Syura",
    arabicName: "الشورى",
    numberOfAyah: "53",
    meaning: "Musyawarah",
    category: "Makiyah",
  },
  {
    id: "surah_43",
    no: "43",
    name: "Az-Zukhruf",
    arabicName: "الزخرف",
    numberOfAyah: "89",
    meaning: "Perhiasan",
    category: "Makiyah",
  },
  {
    id: "surah_44",
    no: "44",
    name: "Ad-Dukhan",
    arabicName: "الدخان",
    numberOfAyah: "59",
    meaning: "Kabut",
    category: "Makiyah",
  },
  {
    id: "surah_45",
    no: "45",
    name: "Al-Jasiyah",
    arabicName: "الجاثية",
    numberOfAyah: "37",
    meaning: "Berlutut",
    category: "Makiyah",
  },
  {
    id: "surah_46",
    no: "46",
    name: "Al-Ahqaf",
    arabicName: "الأحقاف",
    numberOfAyah: "35",
    meaning: "Bukit Pasir",
    category: "Madaniyah",
  },
  {
    id: "surah_47",
    no: "47",
    name: "Muhammad",
    arabicName: "محمّد",
    numberOfAyah: "38",
    meaning: "Muhammad",
    category: "Madaniyah",
  },
  {
    id: "surah_48",
    no: "48",
    name: "Al-Fath",
    arabicName: "الفتح",
    numberOfAyah: "29",
    meaning: "Kemenangan",
    category: "Madaniyah",
  },
  {
    id: "surah_49",
    no: "49",
    name: "Al-Hujurat",
    arabicName: "الحجرٰت",
    numberOfAyah: "18",
    meaning: "Kamar-Kamar",
    category: "Makiyah",
  },
  {
    id: "surah_50",
    no: "50",
    name: "Qaf",
    arabicName: "ق",
    numberOfAyah: "45",
    meaning: "Qaf",
    category: "Makiyah",
  },
  {
    id: "surah_51",
    no: "51",
    name: "Az-Zariyat",
    arabicName: "الذّٰريٰت",
    numberOfAyah: "60",
    meaning: "Angin yang Menerbangkan",
    category: "Makiyah",
  },
  {
    id: "surah_52",
    no: "52",
    name: "At-Tur",
    arabicName: "الطور",
    numberOfAyah: "49",
    meaning: "Bukit Tursina",
    category: "Makiyah",
  },
  {
    id: "surah_53",
    no: "53",
    name: "An-Najm",
    arabicName: "النجم",
    numberOfAyah: "62",
    meaning: "Bintang",
    category: "Makiyah",
  },
  {
    id: "surah_54",
    no: "54",
    name: "Al-Qamar",
    arabicName: "القمر",
    numberOfAyah: "55",
    meaning: "Bulan",
    category: "Makiyah",
  },
  {
    id: "surah_55",
    no: "55",
    name: "Ar-Rahman",
    arabicName: "الرحمن",
    numberOfAyah: "78",
    meaning: "Maha Pengasih",
    category: "Madaniyah",
  },
  {
    id: "surah_56",
    no: "56",
    name: "Al-Waqi'ah",
    arabicName: "الواقعة",
    numberOfAyah: "96",
    meaning: "Hari Kiamat",
    category: "Makiyah",
  },
  {
    id: "surah_57",
    no: "57",
    name: "Al-Hadid",
    arabicName: "الحديد",
    numberOfAyah: "29",
    meaning: "Besi",
    category: "Madaniyah",
  },
  {
    id: "surah_58",
    no: "58",
    name: "Al-Mujadalah",
    arabicName: "المجادلة",
    numberOfAyah: "22",
    meaning: "Gugatan",
    category: "Madaniyah",
  },
  {
    id: "surah_59",
    no: "59",
    name: "Al-Hasyr",
    arabicName: "الحشر",
    numberOfAyah: "24",
    meaning: "Pengusiran",
    category: "Madaniyah",
  },
  {
    id: "surah_60",
    no: "60",
    name: "Al-Mumtahanah",
    arabicName: "الممتحنة",
    numberOfAyah: "13",
    meaning: "Wanita Yang Diuji",
    category: "Madaniyah",
  },
  {
    id: "surah_61",
    no: "61",
    name: "As-Saff",
    arabicName: "الصّفّ",
    numberOfAyah: "14",
    meaning: "Barisan",
    category: "Madaniyah",
  },
  {
    id: "surah_62",
    no: "62",
    name: "Al-Jumu'ah",
    arabicName: "الجمعة",
    numberOfAyah: "11",
    meaning: "Jumat",
    category: "Madaniyah",
  },
  {
    id: "surah_63",
    no: "63",
    name: "Al-Munafiqun",
    arabicName: "المنٰفقون",
    numberOfAyah: "11",
    meaning: "Orang-Orang Munafik",
    category: "Madaniyah",
  },
  {
    id: "surah_64",
    no: "64",
    name: "At-Tagabun",
    arabicName: "التغابن",
    numberOfAyah: "18",
    meaning: "Pengungkapan Kesalahan",
    category: "Madaniyah",
  },
  {
    id: "surah_65",
    no: "65",
    name: "At-Talaq",
    arabicName: "الطلاق",
    numberOfAyah: "12",
    meaning: "Talak",
    category: "Madaniyah",
  },
  {
    id: "surah_66",
    no: "66",
    name: "At-Tahrim",
    arabicName: "التحريم",
    numberOfAyah: "12",
    meaning: "Pengharaman",
    category: "Madaniyah",
  },
  {
    id: "surah_67",
    no: "67",
    name: "Al-Mulk",
    arabicName: "الملك",
    numberOfAyah: "30",
    meaning: "Kerajaan",
    category: "Makiyah",
  },
  {
    id: "surah_68",
    no: "68",
    name: "Al-Qalam",
    arabicName: "القلم",
    numberOfAyah: "52",
    meaning: "Pena",
    category: "Makiyah",
  },
  {
    id: "surah_69",
    no: "69",
    name: "Al-Haqqah",
    arabicName: "الحاۤقّة",
    numberOfAyah: "52",
    meaning: "Hari Kiamat",
    category: "Makiyah",
  },
  {
    id: "surah_70",
    no: "70",
    name: "Al-Ma'arij",
    arabicName: "المعارج",
    numberOfAyah: "44",
    meaning: "Tempat Naik",
    category: "Makiyah",
  },
  {
    id: "surah_71",
    no: "71",
    name: "Nuh",
    arabicName: "نوح",
    numberOfAyah: "28",
    meaning: "Nuh",
    category: "Makiyah",
  },
  {
    id: "surah_72",
    no: "72",
    name: "Al-Jinn",
    arabicName: "الجن",
    numberOfAyah: "28",
    meaning: "Jin",
    category: "Makiyah",
  },
  {
    id: "surah_73",
    no: "73",
    name: "Al-Muzzammil",
    arabicName: "المزّمّل",
    numberOfAyah: "20",
    meaning: "Orang Yang Berselimut",
    category: "Makiyah",
  },
  {
    id: "surah_74",
    no: "74",
    name: "Al-Muddassir",
    arabicName: "المدّثّر",
    numberOfAyah: "56",
    meaning: "Orang Yang Berkemul",
    category: "Makiyah",
  },
  {
    id: "surah_75",
    no: "75",
    name: "Al-Qiyamah",
    arabicName: "القيٰمة",
    numberOfAyah: "40",
    meaning: "Hari Kiamat",
    category: "Makiyah",
  },
  {
    id: "surah_76",
    no: "76",
    name: "Al-Insan",
    arabicName: "الإنسان",
    numberOfAyah: "31",
    meaning: "Manusia",
    category: "Madaniyah",
  },
  {
    id: "surah_77",
    no: "77",
    name: "Al-Mursalat",
    arabicName: "المرسلٰت",
    numberOfAyah: "50",
    meaning: "Malaikat Yang Diutus",
    category: "Makiyah",
  },
  {
    id: "surah_78",
    no: "78",
    name: "An-Naba'",
    arabicName: "النبأ",
    numberOfAyah: "40",
    meaning: "Berita Besar",
    category: "Makiyah",
    page: 22,
  },
  {
    id: "surah_79",
    no: "79",
    name: "An-Nazi'at",
    arabicName: "النّٰزعٰت",
    numberOfAyah: "46",
    meaning: "Malaikat Yang Mencabut",
    category: "Makiyah",
    page: 21,
  },
  {
    id: "surah_80",
    no: "80",
    name: "'Abasa",
    arabicName: "عبس",
    numberOfAyah: "42",
    meaning: "Bermuka Masam",
    category: "Makiyah",
    page: 19,
  },
  {
    id: "surah_81",
    no: "81",
    name: "At-Takwir",
    arabicName: "التكوير",
    numberOfAyah: "29",
    meaning: "Penggulungan",
    category: "Makiyah",
    page: 18,
  },
  {
    id: "surah_82",
    no: "82",
    name: "Al-Infitar",
    arabicName: "الانفطار",
    numberOfAyah: "19",
    meaning: "Terbelah",
    category: "Makiyah",
    page: 17,
  },
  {
    id: "surah_83",
    no: "83",
    name: "Al-Mutaffifin",
    arabicName: "المطفّفين",
    numberOfAyah: "36",
    meaning: "Orang-Orang Curang",
    category: "Makiyah",
    page: 17,
  },
  {
    id: "surah_84",
    no: "84",
    name: "Al-Insyiqaq",
    arabicName: "الانشقاق",
    numberOfAyah: "25",
    meaning: "Terbelah",
    category: "Makiyah",
    page: 15,
  },
  {
    id: "surah_85",
    no: "85",
    name: "Al-Buruj",
    arabicName: "البروج",
    numberOfAyah: "22",
    meaning: "Gugusan Bintang",
    category: "Makiyah",
    page: 14,
  },
  {
    id: "surah_86",
    no: "86",
    name: "At-Tariq",
    arabicName: "الطارق",
    numberOfAyah: "17",
    meaning: "Yang Datang Di Malam Hari",
    category: "Makiyah",
    page: 13,
  },
  {
    id: "surah_87",
    no: "87",
    name: "Al-A'la",
    arabicName: "الأعلى",
    numberOfAyah: "19",
    meaning: "Maha Tinggi",
    category: "Makiyah",
    page: 13,
  },
  {
    id: "surah_88",
    no: "88",
    name: "Al-Gasyiyah",
    arabicName: "الغاشية",
    numberOfAyah: "26",
    meaning: "Hari Kiamat",
    category: "Makiyah",
    page: 12,
  },
  {
    id: "surah_89",
    no: "89",
    name: "Al-Fajr",
    arabicName: "الفجر",
    numberOfAyah: "30",
    meaning: "Fajar",
    category: "Makiyah",
    page: 11,
  },
  {
    id: "surah_90",
    no: "90",
    name: "Al-Balad",
    arabicName: "البلد",
    numberOfAyah: "20",
    meaning: "Negeri",
    category: "Makiyah",
    page: 10,
  },
  {
    id: "surah_91",
    no: "91",
    name: "Asy-Syams",
    arabicName: "الشمس",
    numberOfAyah: "15",
    meaning: "Matahari",
    category: "Makiyah",
    page: 9,
  },
  {
    id: "surah_92",
    no: "92",
    name: "Al-Lail",
    arabicName: "الّيل",
    numberOfAyah: "21",
    meaning: "Malam",
    category: "Makiyah",
    page: 9,
  },
  {
    id: "surah_93",
    no: "93",
    name: "Ad-Duha",
    arabicName: "الضحى",
    numberOfAyah: "11",
    meaning: "Duha",
    category: "Makiyah",
    page: 8,
  },
  {
    id: "surah_94",
    no: "94",
    name: "Asy-Syarh",
    arabicName: "الشرح",
    numberOfAyah: "8",
    meaning: "Lapang",
    category: "Makiyah",
    page: 8,
  },
  {
    id: "surah_95",
    no: "95",
    name: "At-Tin",
    arabicName: "التين",
    numberOfAyah: "8",
    meaning: "Buah Tin",
    category: "Makiyah",
    page: 7,
  },
  {
    id: "surah_96",
    no: "96",
    name: "Al-'Alaq",
    arabicName: "العلق",
    numberOfAyah: "19",
    meaning: "Segumpal Darah",
    category: "Makiyah",
    page: 7,
  },
  {
    id: "surah_97",
    no: "97",
    name: "Al-Qadr",
    arabicName: "القدر",
    numberOfAyah: "5",
    meaning: "Kemuliaan",
    category: "Makiyah",
    page: 6,
  },
  {
    id: "surah_98",
    no: "98",
    name: "Al-Bayyinah",
    arabicName: "البيّنة",
    numberOfAyah: "8",
    meaning: "Bukti Nyata",
    category: "Madaniyah",
    page: 6,
  },
  {
    id: "surah_99",
    no: "99",
    name: "Az-Zalzalah",
    arabicName: "الزلزلة",
    numberOfAyah: "8",
    meaning: "Guncangan",
    category: "Madaniyah",
    page: 5,
  },
  {
    id: "surah_100",
    no: "100",
    name: "Al-'Adiyat",
    arabicName: "العٰديٰت",
    numberOfAyah: "11",
    meaning: "Kuda Yang Berlari Kencang",
    category: "Makiyah",
    page: 5,
  },
  {
    id: "surah_101",
    no: "101",
    name: "Al-Qari'ah",
    arabicName: "القارعة",
    numberOfAyah: "11",
    meaning: "Hari Kiamat",
    category: "Makiyah",
    page: 4,
  },
  {
    id: "surah_102",
    no: "102",
    name: "At-Takasur",
    arabicName: "التكاثر",
    numberOfAyah: "8",
    meaning: "Bermegah-Megahan",
    category: "Makiyah",
    page: 4,
  },
  {
    id: "surah_103",
    no: "103",
    name: "Al-'Asr",
    arabicName: "العصر",
    numberOfAyah: "3",
    meaning: "Asar",
    category: "Makiyah",
    page: 3,
  },
  {
    id: "surah_104",
    no: "104",
    name: "Al-Humazah",
    arabicName: "الهمزة",
    numberOfAyah: "9",
    meaning: "Pengumpat",
    category: "Makiyah",
    page: 3,
  },
  {
    id: "surah_105",
    no: "105",
    name: "Al-Fil",
    arabicName: "الفيل",
    numberOfAyah: "5",
    meaning: "Gajah",
    category: "Makiyah",
    page: 3,
  },
  {
    id: "surah_106",
    no: "106",
    name: "Quraisy",
    arabicName: "قريش",
    numberOfAyah: "4",
    meaning: "Quraisy",
    category: "Makiyah",
    page: 2,
  },
  {
    id: "surah_107",
    no: "107",
    name: "Al-Ma'un",
    arabicName: "الماعون",
    numberOfAyah: "7",
    meaning: "Barang Yang Berguna",
    category: "Makiyah",
    page: 2,
  },
  {
    id: "surah_108",
    no: "108",
    name: "Al-Kausar",
    arabicName: "الكوثر",
    numberOfAyah: "3",
    meaning: "Pemberian Yang Banyak",
    category: "Makiyah",
    page: 2,
  },
  {
    id: "surah_109",
    no: "109",
    name: "Al-Kafirun",
    arabicName: "الكٰفرون",
    numberOfAyah: "6",
    meaning: "Orang-Orang kafir",
    category: "Makiyah",
    page: 1,
  },
  {
    id: "surah_110",
    no: "110",
    name: "An-Nasr",
    arabicName: "النصر",
    numberOfAyah: "3",
    meaning: "Pertolongan",
    category: "Madaniyah",
    page: 1,
  },
  {
    id: "surah_111",
    no: "111",
    name: "Al-Lahab",
    arabicName: "اللهب",
    numberOfAyah: "5",
    meaning: "Api Yang Bergejolak",
    category: "Makiyah",
    page: 1,
  },
  {
    id: "surah_112",
    no: "112",
    name: "Al-Ikhlas",
    arabicName: "الإخلاص",
    numberOfAyah: "4",
    meaning: "Ikhlas",
    category: "Makiyah",
    page: 0,
  },
  {
    id: "surah_113",
    no: "113",
    name: "Al-Falaq",
    arabicName: "الفلق",
    numberOfAyah: "5",
    meaning: "Subuh",
    category: "Makiyah",
    page: 0,
  },
  {
    id: "surah_114",
    no: "114",
    name: "An-Nas",
    arabicName: "الناس",
    numberOfAyah: "6",
    meaning: "Manusia",
    category: "Makiyah",
    page: 0,
  },
];
